### ISSUE TITLE
[Error] The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by tdiekel-in-tech** [afri-bit/vsconan#23] opened 2022-07-21 11:36 UTC
Hi, 

I've got an error when using `pythonInterpreter` with a python venv and a custom conan user home. 

Here my user settings.json: 
```
"vsconan.general.pythonInterpreter": "C:/pyvenv_conan/Scripts/python.exe",
"vsconan.general.conanExecutionMode": "pythonInterpreter",
"vsconan.general.conanUserHome": "C:/Users/user/.conan",
```
My workspace settings.json is empty. 

When I try to refresh I get the error `The "path" argument must be of type string. Received undefined`. I've also checked using double backslashes for the paths. I assume the problem here is that the `conan.exe` lies next to the `python.exe` inside the venv unlike for a normal python installation. 

Best regards

**Comment by tdiekel-in-tech** [comment] 2022-07-21 11:59
Update: 

The error seems to be raised by 
`python.exe -m conans.conan search --raw --json C:\Users\user\.vsconan\temp\recipe.json`.

**Comment by afri-bit** [comment] 2022-07-21 16:08
Hi @tdiekel-in-tech,
thanks for the bug report, I will take a closer look about this issue, and come back to you asap.

**Comment by afri-bit** [comment] 2022-07-21 18:44
Hi @tdiekel-in-tech,
unfortunately I was not able to reproduce the error you mentioned in this issue.

Which version are you using right now? 

> Update:
> 
> The error seems to be raised by `python.exe -m conans.conan search --raw --json C:\Users\user\.vsconan\temp\recipe.json`.
This error could happen, if the path to `python.exe` you defined is not found or the path is incorrect. Could you please check it once again? And maybe can you also provide me the complete error message from vscode message box.

**Comment by tdiekel-in-tech** [comment] 2022-08-01 05:57
Hi, 

I'm using version `0.3.0`. I've reset everything to default and deleted the `C:\Users\user\.vsconan` folder. With the settings

```
    "vsconan.general.conanExecutionMode": "pythonInterpreter",
    "vsconan.general.pythonInterpreter": "C:\\pyvenv_conan\\Scripts\\python.exe",
    "vsconan.general.conanUserHome": "C:\\Users\\user\\.conan",
```

I get no error on the initial start of the extension. After I use the refresh button I get:

```
The "path" argument must be of type string. Received undefined
```

Which I resolved by removing the line `"vsconan.general.conanUserHome": "C:\\Users\\user\\.conan",` from the settings. Now the addon works as expected. 

Unfortunately I was also not able to reproduce the error with the previous settings. Possibly it was just a typo within my settings. Since when using the global python interpreter path which has a space in it I a similar error. The setting `"vsconan.general.pythonInterpreter": "C:\\Program Files\\Python39\\python.exe", ` resulted in the errors

```
Command failed: C:\Program Files\Python39\python.exe -m conans.conan profile list --json C:\Users\user\.vsconan\temp\profile.json
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

```
Command failed: C:\Program Files\Python39\python.exe -m conans.conan search --raw --json C:\Users\user\.vsconan\temp\recipe.json
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

which are at least about the same command failing. Adding `\"` around the path solved those errors. 

I remember faintly that the previous error were about Conan not receiving the path to the file `C:\Users\user\.vsconan\temp\recipe.json` which would result in `conan search: error: argument -j/--json: expected one argument`. But I don't know how to reproduce this error. 

I hope this helps any way. I will leave the issue for you to close in case you want to investigate further.

**Comment by afri-bit** [comment] 2022-09-03 08:54
Hi,
thanks again for your detailed feedback.

Sorry for the very late response, I did not manage to continue working on this project for the past weeks.

I will keep this issue open for further investigations.

**Comment by afri-bit** [comment] 2024-02-17 23:26
Closing for clean up

**Closed by afri-bit** 2024-02-17 23:26 UTC
Labels: under investigation
